# Generated by Django 4.2.23 on 2025-07-06 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libro.libro', verbose_name='Libro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.prestamo', verbose_name='Prestamo')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
